### ISSUE TITLE
rsyslogd: cannot create '/dev/log'

### ISSUE THREAD

**Issue by VoordeMensen** [shamil/docker-postfix-relay#6]
I can't get this package to log to rsyslogd, any suggestions?

```
mail | 2020-12-02 11:34:56 rsyslogd: cannot create '/dev/log': Address in use [v8.1911.0 try https://www.rsyslog.com/e/2176 ]
mail | 2020-12-02 11:34:56 rsyslogd: imuxsock does not run because we could not aquire any socket  [v8.1911.0]
mail | 2020-12-02 11:34:56 rsyslogd: activation of module imuxsock failed [v8.1911.0]
```

**Comment by shamil** [comment]
Can you give more information about what you trying to do?

**Comment by VoordeMensen** [comment]
Ofcourse: I'm trying to expand rsyslogd to log to Papertrail. But it seems that logging is not working at all, when the systeem boots this error occurs in my console (even before me changing configuration). I guess you should see the same error? About `/dev/log` missing?

**Comment by VoordeMensen** [comment]
Resolved. It’s an issue with Digital Ocean app platform, they have their own stdout/err implementation and no /dev/log
